// Generated by scripts/optimize-posters.mjs from public corpus video pointers.
// Original uploader previews; source poster/video URLs remain attribution, not a license grant.
export const media = {
  "asteroid-destroyer": {
    "video": "https://www.youtube.com/watch?v=SYPQo4-P5J0",
    "poster": "https://i.ytimg.com/vi/SYPQo4-P5J0/hqdefault.jpg",
    "localPoster": "/media/posters/asteroid-destroyer-480.webp",
    "posterSrcset": "/media/posters/asteroid-destroyer-320.webp 320w, /media/posters/asteroid-destroyer-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 6265,
    "variants": [
      {
        "src": "/media/posters/asteroid-destroyer-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 2514
      },
      {
        "src": "/media/posters/asteroid-destroyer-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 5898
      }
    ]
  },
  "connected-earth-museum": {
    "video": "https://youtu.be/hOUBkhFR_cE",
    "poster": "https://i.ytimg.com/vi/hOUBkhFR_cE/hqdefault.jpg",
    "localPoster": "/media/posters/connected-earth-museum-480.webp",
    "posterSrcset": "/media/posters/connected-earth-museum-320.webp 320w, /media/posters/connected-earth-museum-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 8791,
    "variants": [
      {
        "src": "/media/posters/connected-earth-museum-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 1382
      },
      {
        "src": "/media/posters/connected-earth-museum-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 3122
      }
    ]
  },
  "grow-team-io": {
    "video": "https://www.youtube.com/watch?v=Q2BKln7vniM",
    "poster": "https://i.ytimg.com/vi/Q2BKln7vniM/hqdefault.jpg",
    "localPoster": "/media/posters/grow-team-io-480.webp",
    "posterSrcset": "/media/posters/grow-team-io-320.webp 320w, /media/posters/grow-team-io-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 15209,
    "variants": [
      {
        "src": "/media/posters/grow-team-io-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 8180
      },
      {
        "src": "/media/posters/grow-team-io-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 15644
      }
    ]
  },
  "landsat-connect": {
    "video": "https://youtu.be/hipj00EOSDI",
    "poster": "https://i.ytimg.com/vi/hipj00EOSDI/hqdefault.jpg",
    "localPoster": "/media/posters/landsat-connect-480.webp",
    "posterSrcset": "/media/posters/landsat-connect-320.webp 320w, /media/posters/landsat-connect-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 7754,
    "variants": [
      {
        "src": "/media/posters/landsat-connect-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 1640
      },
      {
        "src": "/media/posters/landsat-connect-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 3086
      }
    ]
  },
  "quakeheroes": {
    "video": "https://www.youtube.com/watch?v=thxLntBLF1I",
    "poster": "https://i.ytimg.com/vi/thxLntBLF1I/hqdefault.jpg",
    "localPoster": "/media/posters/quakeheroes-480.webp",
    "posterSrcset": "/media/posters/quakeheroes-320.webp 320w, /media/posters/quakeheroes-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 13192,
    "variants": [
      {
        "src": "/media/posters/quakeheroes-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 7650
      },
      {
        "src": "/media/posters/quakeheroes-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 12280
      }
    ]
  },
  "skyshield-wmpgang": {
    "video": "https://youtu.be/RBl_3ZsmVFo",
    "poster": "https://i.ytimg.com/vi/RBl_3ZsmVFo/hqdefault.jpg",
    "localPoster": "/media/posters/skyshield-wmpgang-480.webp",
    "posterSrcset": "/media/posters/skyshield-wmpgang-320.webp 320w, /media/posters/skyshield-wmpgang-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 10078,
    "variants": [
      {
        "src": "/media/posters/skyshield-wmpgang-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 4680
      },
      {
        "src": "/media/posters/skyshield-wmpgang-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 9764
      }
    ]
  },
  "waterwise": {
    "video": "https://www.youtube.com/watch?v=Wg-gE3kYaas",
    "poster": "https://i.ytimg.com/vi/Wg-gE3kYaas/hqdefault.jpg",
    "localPoster": "/media/posters/waterwise-480.webp",
    "posterSrcset": "/media/posters/waterwise-320.webp 320w, /media/posters/waterwise-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 12520,
    "variants": [
      {
        "src": "/media/posters/waterwise-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 6114
      },
      {
        "src": "/media/posters/waterwise-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 11546
      }
    ]
  },
  "hercode-space": {
    "video": "https://youtu.be/1C9ueho9ero",
    "poster": "https://i.ytimg.com/vi/1C9ueho9ero/hqdefault.jpg",
    "localPoster": "/media/posters/hercode-space-480.webp",
    "posterSrcset": "/media/posters/hercode-space-320.webp 320w, /media/posters/hercode-space-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 8034,
    "variants": [
      {
        "src": "/media/posters/hercode-space-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 3644
      },
      {
        "src": "/media/posters/hercode-space-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 7052
      }
    ]
  },
  "pureflow": {
    "video": "https://youtu.be/hHUpo7bTVuc",
    "poster": "https://i.ytimg.com/vi/hHUpo7bTVuc/hqdefault.jpg",
    "localPoster": "/media/posters/pureflow-480.webp",
    "posterSrcset": "/media/posters/pureflow-320.webp 320w, /media/posters/pureflow-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 10736,
    "variants": [
      {
        "src": "/media/posters/pureflow-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 5708
      },
      {
        "src": "/media/posters/pureflow-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 9896
      }
    ]
  },
  "quenaris": {
    "video": "https://youtu.be/QvbLhHqKULc",
    "poster": "https://i.ytimg.com/vi/QvbLhHqKULc/hqdefault.jpg",
    "localPoster": "/media/posters/quenaris-480.webp",
    "posterSrcset": "/media/posters/quenaris-320.webp 320w, /media/posters/quenaris-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 17937,
    "variants": [
      {
        "src": "/media/posters/quenaris-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 10346
      },
      {
        "src": "/media/posters/quenaris-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 20966
      }
    ]
  },
  "resonant-exoplanets": {
    "video": "https://www.youtube.com/watch?v=5fBB5YJpfwU",
    "poster": "https://i.ytimg.com/vi/5fBB5YJpfwU/hqdefault.jpg",
    "localPoster": "/media/posters/resonant-exoplanets-480.webp",
    "posterSrcset": "/media/posters/resonant-exoplanets-320.webp 320w, /media/posters/resonant-exoplanets-480.webp 480w",
    "width": 480,
    "height": 360,
    "sourceWidth": 480,
    "sourceHeight": 360,
    "sourceBytes": 22552,
    "variants": [
      {
        "src": "/media/posters/resonant-exoplanets-320.webp",
        "width": 320,
        "height": 240,
        "bytes": 6174
      },
      {
        "src": "/media/posters/resonant-exoplanets-480.webp",
        "width": 480,
        "height": 360,
        "bytes": 10978
      }
    ]
  }
};
