// Refresh attributed public video previews; never load the private overlay.
import { mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { loadCorpus, publicCorpus } from '../cli/lib.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(resolve(root, 'web/package.json'));
const sharp = require('sharp');
const output = resolve(root, 'web/public/media/posters');
const media = {};
await mkdir(output, { recursive: true });

for (const project of publicCorpus(loadCorpus(root, { includePrivate: false })).projects) {
  if (!project.links?.video) continue;
  const video = new URL(project.links.video);
  if (!['www.youtube.com', 'youtube.com', 'youtu.be'].includes(video.hostname)) continue;
  const id = video.hostname === 'youtu.be' ? video.pathname.slice(1) : video.searchParams.get('v');
  if (!/^[A-Za-z0-9_-]{11}$/.test(id ?? '')) continue;
  if (!/^[a-z0-9-]+$/.test(project.slug)) throw new Error(`Invalid public slug: ${project.slug}`);
  const poster = `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
  const source = new URL(poster);
  if (source.protocol !== 'https:' || source.hostname !== 'i.ytimg.com') throw new Error('Disallowed poster host');
  const response = await fetch(source, { redirect: 'error', signal: AbortSignal.timeout(30000) });
  if (!response.ok || !response.headers.get('content-type')?.startsWith('image/jpeg')) {
    throw new Error(`Invalid poster response for ${project.slug}: ${response.status}`);
  }
  const input = Buffer.from(await response.arrayBuffer());
  if (input.length > 2_000_000) throw new Error(`Poster exceeds size limit: ${project.slug}`);
  const original = await sharp(input).metadata();
  if (!original.width || !original.height) throw new Error(`Missing dimensions: ${project.slug}`);
  const widths = [320, 480, 960].filter((width) => width <= original.width);
  if (!widths.length) throw new Error(`Source is too small: ${project.slug}`);
  const variants = [];
  for (const width of widths) {
    const { data, info } = await sharp(input).resize({ width, withoutEnlargement: true }).webp({ quality: 76, effort: 6 }).toBuffer({ resolveWithObject: true });
    const filename = `${project.slug}-${width}.webp`;
    await writeFile(resolve(output, filename), data);
    variants.push({ src: `/media/posters/${filename}`, width: info.width, height: info.height, bytes: data.length });
  }
  const largest = variants.at(-1);
  media[project.slug] = {
    video: project.links.video, poster,
    localPoster: largest.src,
    posterSrcset: variants.map(({ src, width }) => `${src} ${width}w`).join(', '),
    width: largest.width, height: largest.height,
    sourceWidth: original.width, sourceHeight: original.height, sourceBytes: input.length,
    variants,
  };
}

await writeFile(resolve(root, 'web/src/lib/media.js'), `// Generated by scripts/optimize-posters.mjs from public corpus video pointers.\n// Original uploader previews; source poster/video URLs remain attribution, not a license grant.\nexport const media = ${JSON.stringify(media, null, 2)};\n`);
const totals = Object.values(media).reduce((sum, asset) => ({
  sourceBytes: sum.sourceBytes + asset.sourceBytes,
  largestBytes: sum.largestBytes + asset.variants.at(-1).bytes,
  smallestBytes: sum.smallestBytes + asset.variants[0].bytes,
  allVariantsBytes: sum.allVariantsBytes + asset.variants.reduce((bytes, variant) => bytes + variant.bytes, 0),
}), { sourceBytes: 0, largestBytes: 0, smallestBytes: 0, allVariantsBytes: 0 });
console.log(JSON.stringify({ posters: Object.keys(media).length, ...totals, savingsPercent: Number((100 * (1 - totals.largestBytes / totals.sourceBytes)).toFixed(1)) }, null, 2));
